import { Montserrat } from "next/font/google";
import "./styling/globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  style: ["normal", "italic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} dark`}
      >
        {children}
      </body>
    </html>
  );
}
